version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - /home/$USER/mongodb/database:/data/db
        ports:
        - 27017:27017
        restart: unless-stopped

# source: https://www.bmc.com/blogs/mongodb-docker-container/